import "./tokens.css"; import "./style.css"; import type { Page, PageManifestEntry } from "./domain/page"; import { getAttachmentUrl, getPage, listPages, searchPages } from "./api/client";
const app = document.querySelector<HTMLDivElement>("#app")!; let entries: PageManifestEntry[] = []; let activeArea: "all" | "university" | "notes" = "all";
const escape = (text: string) => text.replace(/[&<>"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" })[char]!);
function layout(content: string) { app.innerHTML = `<div class="shell"><aside class="rail glass"><p class="brand">Knowledge<br>Hub</p><nav class="nav"><button data-area="all" class="${activeArea === "all" ? "active" : ""}">Archive</button><button data-area="university" class="${activeArea === "university" ? "active" : ""}">University</button><button data-area="notes" class="${activeArea === "notes" ? "active" : ""}">Notes</button><button data-view="graph">Graph</button></nav></aside><main class="main"><header class="topbar"><div><p class="eyebrow">Private archive</p><h1>${activeArea === "all" ? "Archive" : activeArea[0].toUpperCase() + activeArea.slice(1)}</h1></div></header>${content}</main></div>`; app.querySelectorAll<HTMLButtonElement>("[data-area]").forEach(button => button.onclick = () => { activeArea = button.dataset.area as typeof activeArea; renderList(entries); }); app.querySelector<HTMLButtonElement>("[data-view=graph]")!.onclick = renderGraph; }
function renderList(items: PageManifestEntry[]) { const visible = activeArea === "all" ? items : items.filter(item => item.area === activeArea); layout(`<input class="search" placeholder="Search..." aria-label="Search archive"><section class="cards">${visible.map(item => `<button class="card" data-id="${item.id}"><p class="tag">${item.area} · ${item.tags.join(", ")}</p><h2>${escape(item.title)}</h2><p>${escape(item.excerpt)}</p></button>`).join("") || "<p>No matching pages.</p>"}</section>`); app.querySelectorAll<HTMLButtonElement>("[data-id]").forEach(button => button.onclick = () => openPage(button.dataset.id!)); app.querySelector<HTMLInputElement>(".search")!.oninput = async event => { const query = (event.target as HTMLInputElement).value; const results = query ? await searchPages(query) : entries; renderList(results); const input = app.querySelector<HTMLInputElement>(".search")!; input.value = query; input.focus(); }; }
async function openPage(id: string) { const page = await getPage(id); const attachments = page.attachments.length ? `<section class="attachments"><h3>Attachments</h3>${page.attachments.map(attachment => `<button data-attachment="${attachment.id}">${escape(attachment.filename)}</button>`).join("")}</section>` : ""; layout(`<article class="reader"><button data-back>← Archive</button><p class="eyebrow">${page.area} · ${page.tags.join(", ")}</p><h2>${escape(page.title)}</h2>${page.body.split(/\n\n+/).map((part, index) => index ? `<p>${escape(part.replace(/^#+\s*/, ""))}</p>` : "").join("")}${attachments}</article>`); app.querySelector<HTMLButtonElement>("[data-back]")!.onclick = () => renderList(entries); app.querySelectorAll<HTMLButtonElement>("[data-attachment]").forEach(button => button.onclick = async () => { const { url } = await getAttachmentUrl(page.id, button.dataset.attachment!); window.location.assign(url); }); }
function renderGraph() { layout(`<svg class="graph" viewBox="0 0 900 600" aria-label="Archive graph">${entries.map((entry, index) => { const x = 120 + (index % 4) * 220; const y = 150 + Math.floor(index / 4) * 220; return `<g class="node" data-id="${entry.id}"><circle cx="${x}" cy="${y}" r="24" fill="${entry.area === "university" ? "#d9e8f6" : "#dce8df"}" stroke="#17375e"/><text x="${x}" y="${y + 48}" text-anchor="middle" font-size="13">${escape(entry.title.slice(0, 24))}</text></g>`; }).join("")}</svg>`); app.querySelectorAll<SVGGElement>(".node").forEach(node => node.onclick = () => openPage(node.dataset.id!)); }
async function authenticate() { app.innerHTML = `<form class="login glass"><p class="eyebrow">Private archive</p><h1>Knowledge Hub</h1><p>Sign in to browse University and Notes.</p><input placeholder="Passphrase" type="password" required><button>Sign in</button><p class="error" hidden></p></form>`; app.querySelector("form")!.onsubmit = async event => { event.preventDefault(); const passphrase = app.querySelector<HTMLInputElement>("input")!.value; const response = await fetch(`${import.meta.env.VITE_API_BASE ?? "/api"}/auth-login`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ passphrase }) }); if (!response.ok) { const error = app.querySelector<HTMLParagraphElement>(".error")!; error.hidden = false; error.textContent = "That passphrase didn’t work."; return; } await boot(); }; }
async function boot() { try { entries = await listPages(); renderList(entries); } catch { authenticate(); } } boot();
