import { readFile } from "node:fs/promises";
import path from "node:path";
import { PageManifestEntrySchema, type Page, type PageManifestEntry } from "../../../src/domain/page";
export function toManifestEntry(page: Page): PageManifestEntry { const plain = page.body.replace(/^#.*$/gm, "").replace(/\s+/g, " ").trim(); return { id: page.id, title: page.title, area: page.area, tags: page.tags, excerpt: plain.slice(0, 157) + (plain.length > 157 ? "..." : "") }; }
export function githubNetworkError(error: unknown) { const cause = error instanceof Error && "cause" in error ? String(error.cause) : String(error); return new Error(`GitHub network error: ${cause}`); }
export type ManifestFileEntry = PageManifestEntry & { path: string };
export function parseManifest(input: unknown): ManifestFileEntry[] { return (input as { path: string }[]).map(item => ({ ...PageManifestEntrySchema.parse(item), path: item.path })); }
export interface DataRepo { listManifest(): Promise<ManifestFileEntry[]>; listPages(): Promise<Page[]>; getPage(id: string): Promise<Page | null> }
class FixtureRepo implements DataRepo { private cache?: Page[]; async listPages(): Promise<Page[]> { if (!this.cache) this.cache = JSON.parse(await readFile(path.join(process.cwd(), "fixtures/seed.json"), "utf8")) as Page[]; return this.cache; } async listManifest() { return (await this.listPages()).map(page => ({ ...toManifestEntry(page), path: `pages/${page.id}.json` })); } async getPage(id: string) { return (await this.listPages()).find(page => page.id === id) ?? null; } }
class GitHubRepo implements DataRepo { constructor(private readonly repo: string, private readonly token: string) {} private async read<T>(file: string): Promise<T> { let r: Response; try { r = await fetch(`https://api.github.com/repos/${this.repo}/contents/${file}`, { headers: { Authorization: `Bearer ${this.token}`, Accept: "application/vnd.github.raw" } }); } catch (error) { throw githubNetworkError(error); } if (!r.ok) throw new Error(`GitHub data repo error ${r.status}: ${file}`); return r.json() as Promise<T>; } async listManifest() { return parseManifest(await this.read<unknown>("manifest.json")); } async listPages() { return Promise.all((await this.listManifest()).map(item => this.read<Page>(item.path))); } async getPage(id: string) { try { return await this.read<Page>(`pages/${id}.json`); } catch { return null; } } }
export function createDataRepo(): DataRepo { return process.env.GITHUB_DATA_REPO && process.env.GITHUB_DATA_REPO_TOKEN ? new GitHubRepo(process.env.GITHUB_DATA_REPO, process.env.GITHUB_DATA_REPO_TOKEN) : new FixtureRepo(); }
